export const GAME_EVENTS = {
  PLAYER_MOVED: "PLAYER_MOVED",
  TARGET_ACQUIRED: "TARGET_ACQUIRED",
  ATTACK_RESOLVED: "ATTACK_RESOLVED",
  LOOT_DROPPED: "LOOT_DROPPED",
  ITEM_EQUIPPED: "ITEM_EQUIPPED",
  XP_GAINED: "XP_GAINED",
  LEVEL_UP: "LEVEL_UP",
  RUN_ENDED: "RUN_ENDED"
} as const;

export type GameEventName = (typeof GAME_EVENTS)[keyof typeof GAME_EVENTS];
